### ISSUE TITLE
XUnit: Assert in action is not failing test

### ISSUE THREAD

**Issue by Osypchuk** [cezarypiatek/NScenario#7]
Provided that my step action is non-async Step is always succeeding, even when Assert located in it is triggered.

I believe it is not a bug in NScenario but somehow related to xUnit way to implement assertions.
(I tried to debug through implementation but I do not see anything wrong)

Here are more detailed steps to reproduce an issue.
Let's start from defining faulty action with Assert in it: 
```
private Action _AssertAction = () =>
{
    Assert.True(false);
};
```
I am expecting step which is using such action to fail. Unfortunately, it is succeeding:
```
[Fact]
public async Task Assert_in_step_action_not_throwing_exception()
{
    var scenario = TestScenarioFactory.Default();
    await scenario.Step("I am assert which should fail", _AssertAction);
}
```

Again, it is not your fault but I would be curious to hear your feedback, maybe it is easy to fix
Full source code: https://github.com/Osypchuk/NScenario/blob/AssertBug/src/NScenario.XUnitDemo/UnitTest1.cs

**Comment by cezarypiatek** [comment]
I guess it was fixed by https://github.com/cezarypiatek/NScenario/pull/8 right?

**Comment by Osypchuk** [comment]
Yes, inital goal of PR was to demonstrate a bug but change in Step fixes it

**Comment by cezarypiatek** [comment]
@Osypchuk  Thank you very much for your contribution
